version: '4.40'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: c12A34t75?
      MYSQL_DATABASE: identificador
      MYSQL_USER: identificador
      MYSQL_PASSWORD: 12345678
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3388:3306" # host:container - default port was changed not to conflict with local mysql server
